---
- name: Install and configure packages on Server
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nano
        - bash-completion
        - iputils-ping
        - net-tools
        - traceroute
        - dnsutils
        - qemu-guest-agent
        - curl
        - unzip
        - ca-certificates
        - gnupg
        - lsb-release

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker’s APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker.list
        state: present

    - name: Update apt package index (again to load Docker's repository)
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose Plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Inform user to log out and log back in
      debug:
        msg: "To apply the group changes, please log out and log back in."

    - name: Run Portainer Agent Docker container
      docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: always
        ports:
          - "9001:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes

    - name: Ensure PubkeyAuthentication is set to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        backrefs: yes

    - name: Ensure PasswordAuthentication is set to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backrefs: yes

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Restart the system
      reboot:
