
version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: ghost_db
    environment:
      MYSQL_ROOT_PASSWORD:  unique_password  # Root password for MariaDB
      MYSQL_DATABASE: ghost                  # Database name for Ghost
      MYSQL_USER: ghost_u                 # Username for Ghost to connect
      MYSQL_PASSWORD: same_but_changepassword       # Password for ghost_user
    volumes:
      - /home/ubuntu/docker/ghost/db:/var/lib/mysql  # Change to your Directory for Persistent storage for MariaDB data
    #ports:
    #  - "3306:3306"  # Expose MariaDB port if needed externally (optional)
    restart: unless-stopped

  ghost:
    image: ghost:latest
    container_name: ghost_app
    environment:
      database__client: mysql
      database__connection__host: ghost_db        # MariaDB container name as the host
      database__connection__user: ghost_u      # Username as defined in mariadb service
      database__connection__password: same_but_changepassword  # Password as defined in mariadb service
      database__connection__database: ghost       # Database name for Ghost
      url: https:/example.com               # URL for the Ghost application
    volumes:
      - /home/ubuntu/docker/ghost/data:/var/lib/ghost/content  # Change to your Directory for Persistent storage for Ghost data
    ports:
      - "2368:2368"  # Expose Ghost's default port
    depends_on:
      - mariadb
    restart: unless-stopped