---
- name: Install Docker, Docker Compose, and Portainer Agent on Debian
  hosts: all  # Replace with the appropriate group or host in your inventory
  become: true
  tasks:

    - name: Ensure lsb-release is installed for codename fact
      apt:
        name: lsb-release
        state: present

    - name: Gather facts after installing lsb-release
      ansible.builtin.setup:
      when: ansible_lsb.codename is not defined

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt and install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      ignore_errors: yes

    - name: Pull Portainer Agent Docker image
      docker_image:
        name: portainer/agent
        tag: latest
        source: pull

    - name: Run Portainer Agent container
      docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: always
        published_ports:
          - 9001:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes

    - name: Display Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Display Docker Compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"
